version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AdminSaad
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: AdminSaad
      # MYSQL_DATABASE: mydatabase
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
   
    

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server
  #   container_name: sqlserver
  #   restart: always
  #   ports:
  #     - 1433:1433
  #   environment:
  #     SA_PASSWORD: AdminSaad19876
  #     ACCEPT_EULA: Y
  #   volumes:
  #     - ./sqlserver_data:/var/opt/mssql

volumes:
  mongodb_data:
  redis_data:
  postgres_data:
  mysql_data:    
