@baseUrl = http://localhost:5000
@urlPath = api/v1


// create department in directorate
###
POST {{baseUrl}}/{{urlPath}}/departments/new
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "قسم الادارة",
    "code": "ق-1",
    "email": "dep-1@inss.com",
    "phone": "3553534534",
    "description": "قسم الادارة هو الجهة المسؤولة عن إدارة الكتب اليومية للمديرية",
    "directorateId": "66e2d7af6f003fa4395a2e53"
}

// create department in organization
###
POST {{baseUrl}}/{{urlPath}}/departments/new
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "قسم الادارة",
    "code": "ق-1",
    "email": "dep-1@inss.com",
    "phone": "3553534534",
    "description": "قسم الادارة هو الجهة المسؤولة عن إدارة الكتب اليومية للدائرة",
    "organizationId": "66e2d78a6f003fa4395a2e4d"
}

// get all departments in directorate
###
GET {{baseUrl}}/{{urlPath}}/departments/directorate/66c37e3107b25d34b6823571
Content-Type: application/json
Accept: application/json
withCredentials: true

// get all departments in organization
###
GET {{baseUrl}}/{{urlPath}}/departments/organization/66e2d78a6f003fa4395a2e4d
Content-Type: application/json
Accept: application/json
withCredentials: true

// get department by id
###
GET {{baseUrl}}/{{urlPath}}/department/66c37e3107b25d34b6823571
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PUT {{baseUrl}}/{{urlPath}}/departments/66c37e3107b25d34b6823571
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "قسم الأمن السيبراني",
    "code": "ق-1",
    "avatar": "https://www.google.com",
    "description": "قسم الأمن السيبراني هو الجهة المسؤولة عن تأمين البنية التحتية للاتصالات و تأمين البيانات الرقمية و الحماية من الهجمات السيبرانية",
    "directorateId": "66c36f498e5fe8f609cf1469"
}

###
DELETE {{baseUrl}}/{{urlPath}}/departments/666ddb95d691500bc70e865c
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/departments/user-count/66a679551ca86ecf5b5204f6
Content-Type: application/json
Accept: application/json
withCredentials: true

