@baseUrl = http://localhost:5000
@urlPath = api/v1



###
POST {{baseUrl}}/{{urlPath}}/organizations/new
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "Organization 1",
    "code": "ORG1",
    "phone": "123456789",
    "email": "org-1@inns.com",
    "address": "123, Street, City, Country",
    "website": "http://localhost:3000",
    "avatar": "https://www.google.com",
    "description": "This is organization 1"
}

###
GET {{baseUrl}}/{{urlPath}}/organizations
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/organizations/66c36d33582b0827065a9415/1
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PUT {{baseUrl}}/{{urlPath}}/organizations/66c36d33582b0827065a9415
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "أمن الأتصالات",
    "code": "ج-36",
    "phone": "123456789",
    "email": "g-36@inns.com",
    "address": "123, Street, City, Country",
    "website": "http://localhost:3000",
    "avatar": "https://www.google.com",
    "description": "دائرة أمن الاتصالات و لأمن السيبراني هي الجهة المسؤولة عن تأمين البنية التحتية للاتصالات و تأمين البيانات الرقمية و الحماية من الهجمات السيبرانية"
}

###
DELETE {{baseUrl}}/{{urlPath}}/organizations/669cfcb80cfdf01ad8744c8d
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/organization/user-count/66c36d33582b0827065a9415
Content-Type: application/json
Accept: application/json
withCredentials: true
