@baseUrl = http://localhost:5000
@urlPath = api/v1



###
POST {{baseUrl}}/{{urlPath}}/auth/new
Content-Type: application/json
Accept: application/json
withCredentials: trues

{
    "userLogin": "101313",
    "password": "123456",
    "avatarColor": "red",
    "username": "سعد ناظم جابر",
    "role": ["66b0eb1489394532782eb1b0","66b0eb0c89394532782eb1af"],
    "rank": "66b0eb602f0d7931d24bc7a7",
    "organizationId": "66b0efb8cae4af434d688da0",
    "departmentId": "66b0efeacae4af434d688da5"
}


###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/auth/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userLogin": "101313",
    "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/auth/logout
Content-Type: application/json
Accept: application/json
withCredentials: true
