@baseUrl = http://localhost:5000
@urlPath = api/v1



###
POST {{baseUrl}}/{{urlPath}}/departments/new
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "Department 1",
    "code": "D-1",
    "email": "dep-1@inss.com",
    "phone": "3553534534",
    "avatar": "https://www.google.com",
    "description": "This is organization 1",
    "organization": "66b1d4ef43c6a0b1d6f49f2a"
}

###
GET {{baseUrl}}/{{urlPath}}/departments/66b1d4ef43c6a0b1d6f49f2a
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/department/669cfdc50cfdf01ad8744c94
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PUT {{baseUrl}}/{{urlPath}}/departments/669cfdc50cfdf01ad8744c94
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "Organization 1",
    "code": "ORG1",
    "slug": "organization-1",
    "avatar": "https://www.google.com",
    "description": "This is organization 1 updated",
    "organization": "669cfca30cfdf01ad8744c88"
}

###
DELETE {{baseUrl}}/{{urlPath}}/departments/666ddb95d691500bc70e865c
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/departments/user-count/66a679551ca86ecf5b5204f6
Content-Type: application/json
Accept: application/json
withCredentials: true

