@baseUrl = http://localhost:5000
@urlPath = api/v1


###
GET {{baseUrl}}/{{urlPath}}/users/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/users/66ab7d673fb2e803f97058ff
Content-Type: application/json
Accept: application/json
withCredentials: true

// Get User Profile
###
GET {{baseUrl}}/{{urlPath}}/users/profile/66abb87d2217037daf968975
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/users/organization/66a679011ca86ecf5b5204ef/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/users/department/66a679551ca86ecf5b5204f6/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/users/search/alsaree
Content-Type: application/json
Accept: application/json
withCredentials: true

// update basic info AuthId
###
###
PUT  {{baseUrl}}/{{urlPath}}/users/update/basic/66a7ae3fa0fb542ee360e5e4
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userLogin": "saad",
    "password": "123456",
    "avatarColor": "red",
    "username": "saad alsaree",
    "role": ["66ad2e229dc1d4c6003fbdef",],
    "rank": "66ad2d5b7798f4db1a913aa8",
    "organizationId": "66a678811ca86ecf5b5204ea",
    "departmentId": "66a679551ca86ecf5b5204f6"
}

// update user info
###
PUT  {{baseUrl}}/{{urlPath}}/users/update/info/66ad47344473998018762eef
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "email": "test13@m14.com",
    "phone": "56654564554",
    "address": "baghdad",
    "work": "developer",
    "displayName": "T.a"

}



// update sttings userId
###
PUT  {{baseUrl}}/{{urlPath}}/users/update/settings/66a7ae3fa0fb542ee360e5e4
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "cases": true,
    "tasks": true,
    "messages": true,
    "comments": true,
    "follows": true,
    "tickets": true
}

// update avatar userId
###
PUT  {{baseUrl}}/{{urlPath}}/users/update/avatar/66a7ae3fa0fb542ee360e5e4
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "avatar": "https://www.w3schools.com/howto/img_avatar.png"
}

// update user is active authId
###
PUT  {{baseUrl}}/{{urlPath}}/users/update/active/66af7b271e12e64e9e9d7f8e
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "isActivated": true
}




